name: simple_auth_app
description: A simple Flutter app demonstrating login functionality using the Cubit pattern for state management.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true